name: Sync Label to Status

on:
  issues:
    types: [labeled]

jobs:
  sync-label-to-status:
    runs-on: ubuntu-latest
    steps:
      - name: Move card to appropriate column when status label added/updated
        if: startsWith(github.event.label.name, 'Status:')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const status = github.event.label.name.replace('Status:', '').trim();
            const projectColumns = await github.rest.projects.listColumns({
              project_id: 1
            });
            const column = projectColumns.data.find(column => column.name.toLowerCase() === status.toLowerCase());
            if (!column) {
              console.log(`Column for status "${status}" not found, skipping`);
              return;
            }
            const issueProjectCards = await github.rest.projects.listCards({
              issue_id: issue.id
            });
            const issueProjectCard = issueProjectCards.data.find(card => card.column_id === column.id);
            if (issueProjectCard) {
              console.log(`Issue already in column "${column.name}", skipping`);
              return;
            }
            await github.rest.projects.moveCard({
              card_id: issueProjectCards.data[0].id,
              position: 'top',
              column_id: column.id
            });
            console.log(`Moved issue to column "${column.name}"`);
            return;
