name: Sync Label to Status

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  sync-label-to-status:
    runs-on: ubuntu-latest
    steps:
      - name: Move card when "in progress" label is added
        if: github.event.action == 'labeled' && github.event.label.name == 'in progress'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;

            // Find all project cards linked to this issue
            const cards = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            for (const project of cards.data) {
              // Get all columns in this project
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              // Find the "In Progress" column
              const inProgressColumn = columns.data.find(column => 
                column.name.toLowerCase() === 'in progress'
              );
              
              if (!inProgressColumn) {
                console.log(`No "In Progress" column found in project ${project.name}`);
                continue;
              }
              
              // Find cards for this issue
              for (const column of columns.data) {
                const cardsInColumn = await github.rest.projects.listCards({
                  column_id: column.id
                });
                
                for (const card of cardsInColumn.data) {
                  if (card.content_url && card.content_url.endsWith(`/${issue.number}`)) {
                    // Move the card to the "In Progress" column
                    if (column.id !== inProgressColumn.id) {
                      await github.rest.projects.moveCard({
                        card_id: card.id,
                        position: 'top',
                        column_id: inProgressColumn.id
                      });
                      console.log(`Moved issue #${issue.number} to "In Progress" column in project ${project.name}`);
                    }
                  }
                }
              }
            }
